name: 'gtfsrt_sandbox'
version: '1.0.0'
config-version: 2

profile: 'gtfsrt_sandbox'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
docs-paths: ["docs"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  gtfsrt_sandbox:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: view
