name: 'gtfsrt_sandbox'
version: '1.0.0'
config-version: 2

profile: 'gtfsrt_sandbox'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
docs-paths: ["docs"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # Feed URLs encoded as base64url (no padding)
  # Default: SEPTA feeds (each feed type needs its own URL)
  vehicle_positions_feed: 'aHR0cHM6Ly93d3czLnNlcHRhLm9yZy9ndGZzcnQvc2VwdGEtcGEtdXMvVmVoaWNsZS9ydFZlaGljbGVQb3NpdGlvbi5wYg'
  trip_updates_feed: 'aHR0cHM6Ly93d3czLnNlcHRhLm9yZy9ndGZzcnQvc2VwdGEtcGEtdXMvVHJpcC9ydFRyaXBVcGRhdGVzLnBi'
  service_alerts_feed: 'aHR0cHM6Ly93d3czLnNlcHRhLm9yZy9ndGZzcnQvc2VwdGEtcGEtdXMvU2VydmljZS9ydFNlcnZpY2VBbGVydHMucGI'
  # directory prefix for where DuckDB should look for raw parquet files
  # if it starts with gs://, will look to GCS 
  parquet_prefix: 'gs://parquet.gtfsrt.io'

  # Date range for data query (adjust to available data)
  start_date: '2026-01-04'
  end_date: '2026-01-04'

models:
  gtfsrt_sandbox:
    staging:
      +materialized: table  # Cache locally to avoid re-downloading
    marts:
      +materialized: view   # Views on top of cached staging tables
